#!/usr/bin/env bash
# nginx server configuration to listen on port 80

# remove default nginx file configuration
rm /etc/nginx/sites-enabled/default

# configure nginx to listen on port 80 for ll IPV4 Ips
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# start nginx
service nginx restart
