#!/usr/bin/env bash
# Loops 10 times and displays:
#   "bad luck" on the 4th iteration
#   "good luck" on the 8th iteration
#   "Best School" for all the other iterations

i=0

while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
        (( i++ ))
done