#!/usr/bin/env bash
# Displays numbers 1 through 20 and:
#   "bad luck from China" on the 4th iteration
#   "bad luck from Japan" on the 9th iteration
#   "bad luck from Italy" on the 17th itration

i=0

while [ $i -le 20 ]
do
    echo "$i"
    case $i in 
        "4") echo "bad luck from China";;
        "9") echo "bad luck from Japan";;
        "17") echo "bad luck from Italy";;
    esac
    (( i++ ))
done